### ISSUE TITLE
Guidance on adding/updating metadata

### ISSUE THREAD

**Issue by borisdayma** [webdataset/webdataset#103]
Hi,

This project is so efficient in loading datasets!

My main question is how to handle adding metadata to large datasets. Do we need to rebuild the tar each time to add/edit associated files or is there a more efficient way?

I'm thinking of something like `zip(wds.Dataset('data_shard.tar'), wds.Dataset('metadata_shard.json'))`.

Metadata dataset could even be any kind of iterator (non wds) but the issue is having workers use the same shards in correct order (even more when shuffling).

**Comment by tmbdev** [comment]
You have three basic options for adding metadata:

1. regenerate the dataset with the new metadata
2. zip up two datasets like you are doing
3. keep the main dataset as webdataset shards but associate the new metadata from a random access file

The simplest and most efficient approach is (1); it ensures that the metadata is always consistent with the samples, it allows self-contained processing of individual shards, and it means that there are no (zero) seeks during loading of each sample.

If your metadata is changing frequently (e.g., some kind of teacher student network etc.), you can put the metadata in a single file or on a distributed database while still reading the bulk of the data from shards. That's approach (3).

You can make approach (2) work but it's the most amount of work. Instead of just using zip, it's best to take keys into account.

### Association Code

```
# fetch metadata from a metadata file
import shelve
os.system("scp server:metadata.shelf .")
metadata = shelve.open("metadata.shelf")

def associate(sample):
    key = sample["__key__"]
    sample.update(metadata[key])
    return sample

dataset = wds.WebDataset(...).decode(...).map(associate)
```

```Python
# fetch metadata from a remote server
import redis, pickle

redis_server = redis.Redis()

def associate(sample):
    key = sample["__key__"]
    sample.update(pickle.loads(redis_server.get(key))
    return sample

dataset = wds.WebDataset(...).decode(...).map(associate)
```
    
    

### Merging Code

*Use only if (1) or (3) really don't work for you.*

```Python
def merge_datasets(ds1, ds2):
    buffer = {}
    for (sample1, sample2) in zip(ds1, ds2):
        assert sample1["__key__"] == sample2["__key__"]
        sample2.update(sample1)
        yield sample2
```

Often a few records get deleted from one or the other dataset, so it's probably a good idea to have any merging code detect that and deal with it.

**Comment by borisdayma** [comment]
Thank you so much for the detailed answer!

**Comment by nicolas-dufour** [comment]
Hi @tmbdev , for option 1, is it possible to do this online (aka without creating a copy but directly adding to the current tar file)

Thanks!

**Comment by tmbdev** [comment]
No, you can't add data to existing files, and that is on purpose: the .tar file is a purely sequential file format guaranteeing that the data can be read and streamed efficiently. If you could add additional files after the fact (e.g., as in .zip files), you couldn't stream the data anymore.

You can combine multiple .tar files into a kind of column store. There is now an example of that in examples/column-store.ipynb
