### ISSUE TITLE
Default error warning

### ISSUE THREAD

**Issue by robvanvolt** [webdataset/webdataset#108]
Hey there, 

we try to push the WebDataset use for large amount of data, and we think it would be a good idea if the error message would be changed to something like "warn and try again N times", when the error is due to interrupted connection. We had many questions on "why does it not work", because the default behavior seemed unintuitive for many users..

What do you think?

**Comment by tmbdev** [comment]
I think it's best not to use the warning mechanism for this. If you need I/O retries due to interrupted connections, just put that into the I/O process. That is, instead of

```
ds = WebDataset("http://.../...")
```

use

```
ds = WebDataset("pipe:curl-with-retries http://.../...")
```

You can use the handler mechanism for this if you really want to; handlers are just callables that get called with an exception object; you can write a class instance with a `__call__` method that keeps track of how often it has been called.
