### ISSUE TITLE
Large size of tar/shard writer output

### ISSUE THREAD

**Issue by huberemanuel** [webdataset/webdataset#115]
I have a text dataset with 20G of data and I tried to use webdataset ShardWriter/TarWriter to convert it. Unfortunately, the initial 20Gb data becomes astonishingly large after the conversion, here are the methods I tried and the output size in the disk.

| Method            | Output Size (Gb) | Data stored                        |
|-------------------|------------------|------------------------------------|
| ShardWritter pth  | 800              | int32 tensors of variable size     |
| ShardWritter pdy  | 300              | Raw text data                      |
| ShardWritter ten  | 260              | int32 numpy array of variable size |
| ShardWritter npy  | 300              | int32 numpy array of variable size |
| ShardWritter json | 300              | Raw text data                      |
| tarp cli          | 210              | Raw text data                      |

Is this the expected behavior? Why a raw data stored in tar files are much larger than the original data?

**Comment by tmbdev** [comment]
> Why a raw data stored in tar files are much larger than the original data?

Without knowing what exactly you are doing, I have to guess.

The only overhead that the tar archive has is the tar headers and the padding to 512 bytes. That  means that each entry has a size of at least 1024 bytes. If your dataset consists only of short texts and you store each text individually, then you may see this kind of expansion.

You have three options for using these kinds of files:

1. store the files as .tar.gz files; the compression will eliminate almost all of the overhead and speed up loading
2. store the data batched; that is, create lists of samples and store them in JSON files; you can unbatch those with ".decode().unlist()"
3. use JSONL or concatenated MessagePack instead of tar archives (the rest of the pipeline remains the same)

(1) will probably fix the problem with the least amount of effort.

(3) is fairly easy but not documented (yet).

**Comment by huberemanuel** [comment]
@tmbdev Thank you for the insightful commentary! 
My files are CVS files each containing a single raw text column. The majority of the samples have less than 1024 bytes, so it seems to be the case.
For the first option, I should concatenate all my separated files into a big one then convert it into a tar.gz? Even with this compression, the webdataset will be able to do random access quickly?

**Comment by tmbdev** [comment]
Yes, your text entries seem to be quite short, so that can account for the blow-up if you store them as individual files within the .tar archive.

As I was saying, there are a number of ways in which you can use WebDataset. The simplest would be to store batches of strings in JSON files (i.e. a list of samples). You can then use a pipeline like: `WebDataset(urls).decode().unlist().shuffle(...).batched(...)`.

To write the file, use something like:

```Python
from more_itertools import chunked
src = open(...)
sink = wds.TarWriter(...)
count = 0
for lines in chunked(src.readlines(), 1024):
    sink.write(dict(__key__=str(count), lines=lines))
    count += len(lines)
sink.close()
```
