### ISSUE TITLE
WebDataset no longer has a length argument (documentation)

### ISSUE THREAD

**Issue by wongjoel** [webdataset/webdataset#125]
In the docs, it's mentioned that "you can specify an explicit size using the `length=` argument to WebDataset"

https://github.com/webdataset/webdataset/blob/2eaa96e6a266ad0ae1a1433e86eb6c2d3b7c50f8/docs/sharding/index.html#L177-L179

This is no longer true, as there is no `length=` argument to WebDataset.

https://github.com/webdataset/webdataset/blob/45724cdfcc0935c63ac6952c5f6b0ada9fa44f37/webdataset/dataset.py#L29-L39

I'm not sure if the documentation is out of date in mentioning a removed parameter, or if the parameter should be there, but got removed accidentally.

**Comment by tmbdev** [comment]
Thanks for the report. The v1 documentation is a bit out of date. Use `webdataset.FakeLength` for setting the length in v1. If you want to force a specific epoch length, use `.repeat().slice(num_samples)`

(In v2, you can use .with_length(n))

The `__len__` method had to be removed because PyTorch considers having a `__len__` method on an `IterableDataset` to be wrong.

**Comment by tmbdev** [comment]
Updated the documentation.
