### ISSUE TITLE
[Documentation Request] How shard size affects performance

### ISSUE THREAD

**Issue by austinmw** [webdataset/webdataset#152]
Hi, I took a subset of the COCO dataset (4096 training images), and tried two different sharding strategies. First I sharded into 8 shards of 512 images each, then I sharded into 64 shards of 64 images each. I set batch size to 16 and num_workers to 8 in wds.WebLoader. 

I noticed that the dataloader operating on the shards of size 64 had a significantly higher throughput (350 images/sec) compared to the dataloader with shards of size 512 (144 images/sec). 

So I'm curious, how should we calculate or estimate the optimal shard size? I did not see any advise in the `sharding.ipynb` example, so maybe that would help others too?

Thanks!

**Comment by tmbdev** [comment]
There are many different factors that affect performance and the optimal shard size.

Generally, you want enough shards so that you have multiple shards for each worker in your job; your total number of workers is the number of nodes or GPUs times the num_workers for each DataLoader. You generally don't want shards that are too small because there can be significant overhead opening shards on remote servers. On the other hand, you want shards that are small enough on your infrastructure to download within a few seconds if they are retrieved over the network.

Usually, shards sizes end up being between around 50 Mbytes to about 10 Gbytes. But don't be afraid to re-shard for your environment.
