### ISSUE TITLE
Best practice for Graph Data (WebDataset + Pytorch Geometric)

### ISSUE THREAD

**Issue by ZikangZhou** [webdataset/webdataset#162]
I'm developing graph neural network applications. Each training sample in my dataset is a graph, and there is a huge number of training samples. Further, I/O is the bottleneck in my applications. For this reason, I try to integrate WebDataset into Pytorch Geometric ([PyG](https://github.com/pyg-team/pytorch_geometric)), the most popular GNN library. I'm looking for the best practice. There are also [discussions](https://github.com/pyg-team/pytorch_geometric/discussions/2864) in the PyG community about the integration of WebDataset.

Typically, a graph can be represented as a **python dictionary** containing node/edge feature tensors and edge index tensors. In PyG, we usually write some complex preprocessing functions to first convert the raw data (e.g., csv/database files) into graphs (i.e., python dictionary containing the necessary graph information), so a preprocessed data sample stored in the file system is actually a dictionary. I believe it's possible to create WebDataset for graphs. Do you have any suggestions on this? Or any recommended way to implement it?

**Comment by tmbdev** [comment]
If your dataset consists of a large number of samples, each containing a graph, you can store each of the graphs either as a Python pickle, a JSON file, a MessagePack, or a CBOR file.

A Python pickle is the simplest, but it can only be read by Python and only with the correct class definition.

Right now, my preferred format is MessagePack, because it's fast, compact, and portable between many languages. But it probably requires converting your data structure.
