### ISSUE TITLE
[Feature request] can we skip some of the steps (useful for resuming a training from stop)

### ISSUE THREAD

**Issue by maxwellzh** [webdataset/webdataset#177]
Currently, when resuming from a stop training, I always have to iterate over some of steps in the epoch with loading the unused data into memory (which is quite time-consuming), can we just skip the steps by setting internal the wds?
e.g.
```
stop_training_step = 5000
for i, minibatch in enumerate(dataloader):
    if i < stop_training_step:
        continue
    ....
```

It seems this feature is not supported by the torch official DataLoader, so I wonder if wds could have this implemented.
Thanks!

**Comment by tmbdev** [comment]
The recommended way is to use the `resampled=True` option to WebDataset or  the `wds.resampled` pipeline stage. That way, you get the same training statistics when you restart your job; no need to skip any samples.

Trying to achieve "each sample exactly once per epoch" is difficult, and it's even more difficult if you try to restart in the middle of an epoch; how you do that depends on whether you use single or multiple nodes, how you use workers, etc. WebDataset gives you the primitves you need (slice, detshuffle, rng= arguments), but it can't do it for you because it doesn't know about the environment you run in.

**Comment by tmbdev** [comment]
I should add that WebDataset is now supported in torchdata and (soon) Ray Data natively. Both of those frameworks have their own ways of dealing with restarting. You may find those useful as well. Nevertheless, the recommended and simplest way is likely still simply to use shard resampling.
