### ISSUE TITLE
Allow writing tiffs using TarWriter

### ISSUE THREAD

**Issue by mchalecki** [webdataset/webdataset#179]
I want to use tiff format because I have binary mask in float32 format which cannot be saved using png, jpg or ppm. The default encoder does not handle tiffs.

I can decode tiffs by using custom decoding function as showed in https://github.com/webdataset/webdataset/issues/56 but i get no way to save them from python using default encoder. I'd have to override default encoder by adding handle for tiff. 
PIL already supports writing tiffs so that should be handled by extending imageencoder in my opinion.

**Comment by mchalecki** [comment]
To make it work I only had to add 
```python
    add_handlers(handlers, "tiff", lambda data: imageencoder(data, "tiff"))
```
in webdataset.writer.make_handlers 
and also not to reduce quality
``` python
    if format in ["JPEG", "tiff"]:
        opts = dict(quality=100)
``` 
in webdataset.writer.imageencoder

**Comment by tmbdev** [comment]
Yes, adding TIFF decoding/encoding is easy for users to do.

The reason it isn't done by default is because TIFF has many format variants and it is difficult to decode it reliably.

The recommended image format for storage is usually JPEG because it's the fastest to decode and there are even hardware decoders for it.
