### ISSUE TITLE
ddp_equalize

### ISSUE THREAD

**Issue by cecabert** [webdataset/webdataset#194]
When using `DDP` during training, the documentation says to use the method `ddp_equalize` to make sure each worker process the same number of batches [[doc](https://webdataset.github.io/webdataset/multinode/#distributeddataparallel)].

However when running this:

```python
urls = "./shards/imagenet-train-{000000..001281}.tar"
dataset_size, batch_size = 1282000, 64
dataset = wds.WebDataset(urls).decode("pil").shuffle(5000).batched(batch_size, partial=False)
loader = wds.WebLoader(dataset, num_workers=4)
loader = loader.ddp_equalize(dataset_size // batch_size)
```

We end up with the following exception `AttributeError: 'WebLoader' object has no attribute 'ddp_equalize'`. Moreover, the test for this functionality has been [disabled](https://github.com/webdataset/webdataset/blob/b0d03fda8bbd687c896c1910bf027bb3d0b31fb4/webdataset/tests/test_xcompat.py#L118). 

I am a bit confused at the moment about what is the right way to use `Webdataset` together with `DDP`, is it still mandatory to call `ddp_equalize` or is the documentation outdated?

**Comment by KaiyuYue** [comment]
Same issue with the latest version. Can the developers give a brief demo to show how to build a pipeline for ddp? Thanks in advance.

**Comment by tmbdev** [comment]
Sorry for not responding earlier. Instead of `.ddp_equalize`, you can simply use `.repeat(2).set_length(n)`. `ddp_equalize` tried to do this for you automatically but lacked the necessary information about choosing `n` correctly. The value of `n` depends on how unequal the expected distribution of samples in different workers may be and what your preferences are about repeated samples in each epoch. Alternatively, you can also just do partial distributed SGD updates.

These issues can't be addressed within WebDataset or the old data framework; `torchdata` is addressing them now, and we're merging all the WebDataset functionality into torchdata.

**Comment by henrique** [comment]
@tmbdev thanks for the comments here and for the great work.
Could you tell us which version the trick you mention above should work? or which version still had `ddp_equalize`?
I 've tried `.repeat(2).with_length(N)` on v0.2.5 (as `set_length` doesn't exist in the latest version?) but still get: `ValueError: input pipeline needs to be reconfigured for multinode training`

Torchdata is looking good but it doesn't seem to return an actual webdataset, and their pipeline doesn't have the `decode` function, for example. I also couldn't find an working example using torchdata and a regular wds for supervised vision, is there any around?
Thanks a lot already for any pointers
Cheers

**Comment by wtliao** [comment]
> @tmbdev thanks for the comments here and for the great work. Could you tell us which version the trick you mention above should work? or which version still had `ddp_equalize`? I 've tried `.repeat(2).with_length(N)` on v0.2.5 (as `set_length` doesn't exist in the latest version?) but still get: `ValueError: input pipeline needs to be reconfigured for multinode training`
> 
> Torchdata is looking good but it doesn't seem to return an actual webdataset, and their pipeline doesn't have the `decode` function, for example. I also couldn't find an working example using torchdata and a regular wds for supervised vision, is there any around? Thanks a lot already for any pointers Cheers

Have you solved this issue? I am stucked here for several days

**Comment by cecabert** [comment]
Hi,

I was not able to make WebDataset work in distributed settings. To solve the issue, I move to `TorchData` as other have previously mentioned. You can look at this [example](https://pytorch.org/data/main/generated/torchdata.datapipes.iter.WebDataset.html) to see how one can put the two together.

**Comment by jpgard** [comment]
@tmbdev thanks for the answer regarding `repeat(2).set_length(n)`, and for your contributions to webdataset, it's an awesome tool. It looks like this answer is also almost verbatim copied into the [FAQ,](https://github.com/webdataset/webdataset/blob/faa774ec4e81cb738a4911691c59b68829505a2a/FAQ.md) but I am still not quite clear on what `n` is doing here, and how exactly to choose it or what considerations would affect the choice and was wondering if you could provide a bit more detail. 

How should I think about selecting `n` relative to number of shards, examples per shard, total dataset length, batch size, num workers? What are the risks of setting `n` to high vs. too low?

**Comment by tmbdev** [comment]
Sorry, the FAQ was wrong. There are two methods:

- `with_length(n)` adds a `__len__` method to the pipeline so that len(dataset) returns n. It does not actually change anything about the data returned by the IterableDataset. This method is fairly obscure and sometimes needed when code uses IterableDataset incorrectly.

- `with_epoch(n)` ensures that the epoch is no longer than n samples. This is used when you want to ensure that each worker in DDP training gets the same number of batches. It is usually combined with `.repeat(2).with_epoch(n)`

Let's say your epoch is normally 1281237 samples, divided among 100 shards, and you have 32 I/O workers total. Since none of those numbers divide nicely, some of the workers get 3 shards each, others get 2 shards each. So, to get the same number of batches while maintaining roughly the epoch size, you use `.repeat(2).with_epoch(1281237 // batch_size)`, which will ensure that each GPU gets the same number of batches, yet epochs are still about 1281237 samples large. However, some batches may be missing/repeated.

This is the most complex and least preferred way of dealing with unequal number of shards per worker. Preferred ways are:

- use resampling; you still use with_epoch; an epoch just becomes the unit of reporting/saving/restarting, and you just pick whatever is convenient for that
- use the PyTorch sync methods and just allow unequal number of samples in different workers
- use the upcoming WebIndexedDataset, which provides an indexed interface to WebDataset and allows you to balance samples perfectly, but at the cost of slightly higher resource usage

**Comment by jpgard** [comment]
Thanks for the reply. I am still not clear on why 2 is chosen for `.repeat(2)` in the example you gave? Why wouldn't we just call `.repeat()`, if I understand correctly that would repeat the dataset forever (with the default value of- -1)? Is that not the case?

**Comment by tmbdev** [comment]
The value 2 should be good enough. If your dataset is so unbalanced that 2 is not good enough, you'll get an error, and that's my preferred behavior.But you can use an infinite repeat as well.
