### ISSUE TITLE
How to skip some tar files?

### ISSUE THREAD

**Issue by TheShadow29** [webdataset/webdataset#200]
Hello, what is the best way to skip some particular keys? If I understand correctly, currently the easiest way is to return None through a map function due to the continue statement here: https://github.com/webdataset/webdataset/blob/main/webdataset/filters.py#L366

Is there any way to avoid reading in the file in the first place? Thanks!

**Comment by tmbdev** [comment]
No, you can't avoid reading the file. That's because in most large scale applications, the file is just read from a network stream, so there is  no benefit to not reading the file. And even if you cache to SSD, reading the file doesn't really cost you anything for typical sample sizes.

However, you can avoid decoding samples that you don't need, and that's recommended. In that case, you need to `map` or `select` before the `decode` statement.

**Comment by TheShadow29** [comment]
@tmbdev If I am understanding correctly, wont adding a "if" statement here: https://github.com/webdataset/webdataset/blob/main/webdataset/tariterators.py#L105 skip reading the file altogether? Not sure if it will speed up the process in any noticeable manner.

**Comment by tmbdev** [comment]
That only skips metadata files (files with names like `__something__`. That's not done for speed but simply to avoid having them mess up downstream processing if the downstream processing can't handle them.

As I was saying, the shards are almost always streamed from somewhere, so it takes the same amount of time skipping the file as reading it.

**Comment by tmbdev** [comment]
Note that if you want to read .tar files from disks and access them sparsely, the `wids` library provides fast random access to .tar files. However, they have to be completely downloaded.
