### ISSUE TITLE
decode ignores extensions for keys that start with "_"

### ISSUE THREAD

**Issue by drscotthawley** [webdataset/webdataset#220]
## Bug: 
Despite having `wds.decode(wds.torch_audio)` as part of my pipeline, webdataset is trying to decode one of my  `.flac` sub-files as utf-8. 

I found the reason for this: in autodecode.py line 446:

```python
          if k[0] == "_":
                if isinstance(v, bytes):
                      v = v.decode("utf-8")
```

The sub-file in question has a key of `_gbia0001334b.flac`.  So the ".flac" is being ignored and instead the leading "`_`" is mistakenly causing the system to try to decode it as utf-8.  Why is this rule about "`_`" hard-coded?  And can it be changed so that it is a fall-back behavior after any other extension-based decodings have been tried first? 

# Expected behavior:

the ".flac" extension should take precedence causing the file to be decoded as flac, and the rule about leading underscores being processed as utf-8 should be deprecated or removed.

**Comment by tmbdev** [comment]
It now checks for .startswith("__"), so your case should work.

Generally, we need some way of passing metadata around, so some part of the namespace needs to be reserved; we adopt the Python convention of leading underscores.

Since metadata right now is all in UTF-8 format, it is automatically decoded as UTF-8 no matter what the extension is.
