### ISSUE TITLE
making subsets of webdatasets

### ISSUE THREAD

**Issue by nicolas-dufour** [webdataset/webdataset#239]
Hi,
I'm wondering if it's possible to filter the webdataset once it has been built.
Like for example, imagine you have the imagenet dataset, and you want to select only a subset of categories. Is it possible to do this efficiently with webdataset? Or do you need to create a new webdataset for each subset (Which would increase storage needs).
I think i saw it's possible to do it if you shard correctly your dataset, but i'm interested in cases where num_classes >> num_shards

Thank you!

**Comment by tmbdev** [comment]
You can select samples with a simple map function:

```
def select(sample):
    if sample["cls"] in [0, 3, 9]:
        return sample
    else:
        return None

dataset = wds.WebDataset(...).decode().map(select)
```

This will be efficient as long as you don't throw away more than 50-80% of the samples (depending on your I/O system and other factors).

If you want smaller subsets of your data, you should create a new WebDataset in order to achieve efficient I/O.

This is not a restriction of the WebDataset API or library, this restriction follows from the way disk storage operates: if you select a small subset of data without creating a new dataset, you need to do lots of random disk accesses, and those are inherently expensive. The WebDataset API is designed to discourage such inefficient usage.
