### ISSUE TITLE
Webdataset or TorchData?

### ISSUE THREAD

**Issue by nicolas-dufour** [webdataset/webdataset#249]
Hi,
Since webdataset has been integrated to torchdata, which is the recommended use? Are the 2 version equivalent? If not, which one do you recommend using?

Thanks!

**Comment by tmbdev** [comment]
The two libraries should be fully compatible and you can use either.

Some of the reasons you might still want to use WebDataset are backwards compatibility and ability to work without Torch.

It should be easy to port from WebDataset to torchdata, since the libraries are very similar in terms of APIs and functionality, so there is no urgency to switch. Also, WebDataset has added extract_keys, rename_keys, and xdecode as torchdata-like interfaces making the pipelines and even more similar.

I'm also adding WebDataset support to Ray and Ray AIR, which gives you a third option and also helps with shuffling and repartitioning.

**Comment by nurpax** [comment]
I came here from the webdataset FAQ that recommends TorchData.  I notice though that TorchData development has paused (quoting from the pytorch/data repository on GitHub):

"As of July 2023, we have paused active development on TorchData and have paused new releases. We have learnt a lot from building it and hearing from users, but also believe we need to re-evaluate the technical design and approach given how much the industry has changed since we began the project. During the rest of 2023 we will be re-evaluating our plans in this space. Please reach out if you suggestions or comments (please use #1196 for feedback)."
