### ISSUE TITLE
How to load a subset of the files in a sample?

### ISSUE THREAD

**Issue by Andreas-Grigoriadis-Qualcomm** [webdataset/webdataset#257]
I have a use case where each sample consist of a main image, with a set of auxiliary images that **may** be used depending on the training configuration. Example of sample:

sample0.main.jpg
sample0.aux0.jpg
sample0.aux1.jpg
sample0.aux2.jpg
sample0.aux3.jpg
sample0.aux4.jpg
...

In my job I specify the number of/which auxiliary images to use. An easy way to accomplish this is to read the sample as normal and disregard the data I will not use, however this means reading in up to potentially 20 times more data than I will use.

Is there a good way of skipping reading some files depending on a configuration?

**Comment by tmbdev** [comment]
I have added a select_files option to WebDataset and tarfiles_to_samples that lets you select the files you want to extract.

Note that in most circumstances, this won't help you all that much, since the necessary seek for skipping data is usually not a lot faster than simply reading the data. This is not a limitation of WebDataset, it is the way hard drives work. Other formats simply pay the overhead of seeking for all types of data, while WebDadtaset gives you faster I/O when your data is fully sequential. The most efficient way of reading data is to pre-select the files you need during training so that your tar files contain exactly and only the files you actually need during training.

**Comment by Andreas-Grigoriadis-Qualcomm** [comment]
Thanks for the support, really appreciated!

**Comment by yifanlu0227** [comment]
But it saves the decoding time for those unread files, right?
