### ISSUE TITLE
[Distributed inference] How to effectively perform it with torch and webdataset

### ISSUE THREAD

**Issue by sayakpaul** [webdataset/webdataset#285]
Is there a guide discussing how to use `webdataset` with PyTorch to run distributed inference (single node multi GPU works)?

**Comment by vishaal27** [comment]
Did anybody manage to find some useful resources for this?

**Comment by mmderakhshani** [comment]
Hi @sayakpaul,  Did you find any solution to this?

**Comment by tmbdev** [comment]
Depends on the application. If you want to do bulk distributed inference, there are two simple approaches:

(1) write a simple shard-to-shard transformation and run that in parallel
(2) perform inference itself in parallel and write to a new set of shards

I usually do (1) because it's the easiest to parallelize and restart. That is, I write something like:

```
def shard_inference(source_shard, dest_shard):
    source = WebDataset(source_shard, ...)
    dest = TarWriter(dest_shard, ...)
    for sample in source:
        sample["result.json"] = ... inference ...
        dest.write(sample)
    dest.close()
    source.close()

def main():
	...
```

You can then run many copies of that shard-to-shard command line program in parallel.

For (2), you can use your favorite multiprocessing framework (I like to use Ray) and just parallelize the inference itself:

```
pool = ray.Pool(...)

@ray.distributed(cpu=4, gpu=1)
def inference_on_sample(sample):
    result = dict(sample, output=inference(sample))
    return result

def shard_inference(source_shard, dest_shard):
    source = WebDataset(source_shard, ...)
    dest = TarWriter(dest_shard, ...)
    for output in pool.map_unordered(inference_on_sample, source):
        dest.write(output)
    dest.close()
    source.close()
```

You can also use Ray or Python multiprocessing to parallelize the `shard_inference` function in approach (1).

Yet another approach is to use Ray's inference engine with Webdataset as the data source; or you can use any of the PyTorch inference frameworks and either use WebDataset or wids.ShardListDataset as input.

**Comment by sayakpaul** [comment]
Thanks for your elaborate reply! Would it be possible to include a simple and end-to-end example in docs about this? I think this is good and practical use case.

**Comment by lilyzhangustc** [comment]
@tmbdev  hi Tom, thanks for the answer! I have a similar question, under single node 8 GPU setup, how to run distributed inference and make sure every sample can be inferred? I have the following code, however I observe the output by each GPU are highly overlapping with each other: `dataset = (
            wds.WebDataset(
                tarurl,
                nodesplitter=wds.split_by_worker,
                shardshuffle=True,
                resampled=False,
            )
            .shuffle(1000)
            .decode()
            .to_tuple("metadata.json")
            .map(xxx)
            .to_tuple(xxx)
            .map_tuple(xxx)
            .batched(self.batch_size, partial=False)
            .with_length(self.dataset_size)
            .repeat(2)
loader = (
            wds.WebLoader(
                dataset,
                batch_size=None,
                shuffle=False,
                num_workers=8
            )
            .unbatched()
            .shuffle(1000)
            .batched(self.batch_size)
            .with_epoch(max(self.dataset_size // (self.batch_size * 8), 1))
        )
`

Thank you so much!
