### ISSUE TITLE
How to pre-download next tar-file (=shard) to prevent training from blocking?

### ISSUE THREAD

**Issue by Oktai15** [webdataset/webdataset#300]
I decided to understand how to use WebDataset for large-scale training when my data is on the cloud. 

I found that it has two ways:
1. Load sample-by-sample from cloud, i.e. I just init `dataset = wds.WebDataset(urls)` and create `DataLoader` on it. It means that I will open stream on my cloud tar file (=one shard) and load sample-by-sample, reading `buffer_size` elements every time and use it. This way is great if I have good download speed.
2. Load whole shard on local disk from cloud, i.e. I init `dataset = wds.WebDataset(urls, cache_dir=cache_dir, cache_size=cache_size)` and create `DataLoader` on it. It means that I download whole tar file when I will need the next one. 

The second way looks promising for me, but it starts the download ONLY when my previous shard was passed through the my model fully. It is not okay, because I am waiting every time the download of the new shard when current shard is exhausted.

In my opinion, it would be cool if WebDataset has `prefetch_factor` for downloading shards or something like that and download next shard whenever previous one at the start of using or at the middle. 

Has this feature already implemented in some way? If not, why?

**Comment by Oktai15** [comment]
@tmbdev, please, take a look at this issue

**Comment by tmbdev** [comment]
Yes, those are the two official ways.

The fact that WebDataset blocks on download with caching isn't really an issue. The prefetching you mention would be an additional mechanism that would avoid blocking, but you can achieve the same effect simply by using a larger num_workers with DataLoader. The "workers" will not consume significant CPU resources while downloading, so increasing it to accommodate downloads doesn't really cost you anything.

Roughly, if you need, say, five workers to meet the CPU requirements of your data loader pipeline and downloading takes 25% of the total processing time for one shard, then simply increase num_workers to about 7.

But you don't have to be precise about it; making num_workers larger than it needs to be just means that workers will spend more time waiting because they have filled up the queue.

**Comment by Oktai15** [comment]
@tmbdev, let’s suppose I train model in multi-gpu mode, I have 2 GPU, I init:
```
dataset = WebDataset(…)
dataloder = Dataloader(num_workers=4)
```
I will have two main processes (1 per GPU) which create 4 additional (dataloder) workers each, i.e. total number of additional workers will be 8.

Every additional worker will have unique shard? Or every main process associated to specific GPU will have unique shard and corresponding N workers read from this shard simultaneously?

**Comment by RoyJames** [comment]
> @tmbdev, let’s suppose I train model in multi-gpu mode, I have 2 GPU, I init:
> 
> ```
> dataset = WebDataset(…)
> dataloder = Dataloader(num_workers=4)
> ```
> 
> I will have two main processes (1 per GPU) which create 4 additional (dataloder) workers each, i.e. total number of additional workers will be 8.
> 
> Every additional worker will have unique shard? Or every main process associated to specific GPU will have unique shard and corresponding N workers read from this shard simultaneously?

If you provided a list of shards, they will be split uniquely for each worker. You can set `verbose=True` for your `WebDataset` and see each worker requesting different shards.

**Comment by RoyJames** [comment]
The `prefetch_factor` parameter in `DataLoader` is 2 by default, so it should technically work when you wrap a `WebDataset` with it. The issue from my view is that this prefetch does not happen on shard level - when you have larger shards, one shard contains multiple batches of data, so that the prefetch is only triggered near the end of a shard. One obvious workaround is to increase the `prefetch_factor`. Ideally, if the time for your model to compute `prefetch_factor-1` batches is longer than the time it takes to download one shard, the training should no longer block. But scaling up `prefetch_factor` may have its own drawback.

**Comment by tmbdev** [comment]
> I will have two main processes (1 per GPU) which create 4 additional (dataloder) workers each, i.e. total number of additional workers will be 8.
> 
> Every additional worker will have unique shard? Or every main process associated to specific GPU will have unique shard and corresponding N workers read from this shard simultaneously?

By default, each worker gets a unique set of shards. The WebDataset class is itself just a pipeline that looks something like this:

```
DataPipeline(
  SimpleShardList(urls),
  single_node_only,
  split_by_worker,
  shuffle(100),
  StreamingOpen(),
  tar_file_expander,
  group_by_keys
)
```

**Comment by kaan-simbe** [comment]
I know the discussion has concluded, but one drawback of simply increasing num_workers to mimic an ahead-of-time download strategy (like MosaicML Streaming’s predownload) is the risk of uneven shard distribution. For instance, if you have 15 shards and raise the worker count from 5 to 7, you might end up with one worker handling an extra shard or, worse, a shard going unused altogether. This also has implications for the shuffling that happens per worker basis.
