### ISSUE TITLE
Possibility to skip files in tar files?

### ISSUE THREAD

**Issue by fferroni** [webdataset/webdataset#307]
Hello,
Is it possible to skip keys altogether when loading the tar file rows into memory?

Assume I have a dataset that contains per "row" a large file (`jpg`) and a small file (`txt`).
I'd like to perform some operations that only touch the small `txt` file.

```
dataset = wds.WebDataset(["path/to/dataset.tar"])
# Define the keys you want to keep
keys_to_keep = ["__key__", "__url__", "txt"]

def filter_keys(sample):
    return {k: sample[k] for k in keys_to_keep if k in sample}

filtered_dataset = dataset.map(filter_keys)
```
The above filters `jpg` but it still actually reads the bytes of the `jpg` file into `sample`. 
Wondering if it's possible to avoid this.

Thanks!

**Comment by guillermojp** [comment]
Hey, @fferroni! I haven't actually tested it in my use cases, but isn't that the intended use of the `select_files` argument in `wds.WebDataset` class? (Or in `wds.tarfile_to_samples` if you're using `wds.DataPipeline`)

**Comment by tmbdev** [comment]
WebDdataset is based on a streaming paradigm; since the bytes stream in, they must be read no matter what.

There is a new interface called "wids" that provides indexed access to WebDataset files. When using it with local files, it only reads data from disk that you actually use. 

Generally speaking, if this causes performance issues for you, your best bet is to generate a new dataset that has only the "columns" or fields that you need.
