### ISSUE TITLE
[REQUEST] Creating a ResampledShardLists class as an alternative to ResampledShards

### ISSUE THREAD

**Issue by Tomsen1410** [webdataset/webdataset#318]
Hello everyone,

I was wondering about the functionality of ResampledShards for multi-node training. As far as I understand it, in the default case each worker computes a different seed and then samples random shards after another individually. This leads to an arbitrary shard distribution during training and might be sub-optimal.

Wouldn't a better alternative be to shuffle the entire shards list before each cycle and then distribute the shards to the workers in a round robin fashion? This essentially leads to a limitless stream of shards, however, distributed much more evenly and more balanced.

```
class ResampledShardLists(IterableDataset):
    def __init__(self, urls, nrepeats=sys.maxsize, shuffle=True, global_seed=None):
        super().__init__()
        urls = wds.shardlists.expand_urls(urls)
        self.urls = urls
        assert isinstance(self.urls[0], str)
        self.nrepeats = nrepeats
        self.shuffle = shuffle
        self.global_seed = global_seed or 1337
        if self.shuffle:
            self.rng = random.Random(self.global_seed)

    def __iter__(self):
        for _ in range(self.nrepeats):
            urls = self.urls.copy()
            if self.shuffle:
                self.rng.shuffle(urls)
            for url in urls:
                yield dict(url=url)
```

This would be some simple class which I am using currently. I think this might be a good alternative to ResampledShards, or am I missing something?

Note: Important is to ensure that each worker uses the same seed.

**Comment by tmbdev** [comment]
Resampling is technically defined as "sampling with replacement" in statistics, so that is what the current system implements. 

You do have the option of using the Pipeline interface to implement what you desire, namely splitting shards among nodes before resampling. The problem with that is that nodes receive unequal numbers of shards, so samples from some shards are overrepresented.

The new `wids` interface avoids all these tradeoffs and lets you partition and sample your datasets at the individual sample level, ignoring all shards and shard boundaries, albeit at the cost of more local disk storage and slightly higher latencies. Have a look at the examples subdirectory for how that works.
