### ISSUE TITLE
wids cannot open SAM dataset

### ISSUE THREAD

**Issue by Lyken17** [webdataset/webdataset#331]
Hi author,

Thanks for designing such a flexible and efficient dataloader. WIDS used to work fine in my training pipelines, however, I recently notice a werid error when loading [SAM dataset](https://ai.meta.com/datasets/segment-anything-downloads/).

```
(vila) ligengz:~/workspace/dev$ python wids_dev.py
[WebShardedList] wids_dev.json base:  name: None nfiles: 2 nbytes: 0 samples: 200 cache: /home/ligengz/.cache/_wids_cache
Traceback (most recent call last):
  File "//VILA/wids_dev.py", line 7, in <module>
    for idx, sample in enumerate(dst):
  File "VILA/llava/wids/wids.py", line 594, in __getitem__
    shard, inner_idx, desc = self.get_shard(index)
  File "VILA/llava/wids/wids.py", line 589, in get_shard
    raise e
  File "VILA/llava/wids/wids.py", line 586, in get_shard
    shard = self.cache.get_shard(url)
  File "VILA/llava/wids/wids.py", line 383, in get_shard
    itf = IndexedTarSamples(path=local, stream=stream)
  File "VILA/llava/wids/wids.py", line 237, in __init__
    self.reader = MMIndexedTar(stream)
  File "VILA/llava/wids/wids_mmtar.py", line 60, in __init__
    self._build_index()
  File "VILA/llava/wids/wids_mmtar.py", line 74, in _build_index
    name = header.name.decode("utf-8").strip("\x00")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Seems like a decoding error when after I untar and re-tar the dataset, it can be loaded properlly.

**Comment by Lyken17** [comment]
I've located the issues, this is because sam dataset is gzipped and the webdataset does not handle the case

```
~/workspace$ gzip -t sa_000000_retar.tar
gzip: dev.tar: not in gzip format

~/workspace$ gzip -t sa_000000.tar
```

**Comment by rwightman** [comment]
@Lyken17 so, this isn't as easy as one might think. tar files are simple, you can just stash the offsets for each file entry and directly access them later. When the data is compressed that no longer works, naively you'd have to fully decompress the file for those offsets to be meaningful.

Many compression formats do have blocks that can be independently decoded (or settings to allow that. If that's the case it's possible to map data of interest to specific blocks so you can skip, but the granularity can be an issue, you still need to decompress a whole block (or more) to get your desired sample... whether that makes any sense would be significalty impacted by the sizing of your samples relative to compression block size, etc.

It's also going to get pretty messy to implement such a feature, for gzip, this tool is a good reference https://github.com/circulosmeos/gztool

**Comment by Lyken17** [comment]
thanks @rwightman for th detailed information.

Yeh I understand that the mmap requires the files to be stored in continual and raw binary streams. But actually the python-tar library support gzip stream already https://docs.python.org/3.10/library/tarfile.html#tarfile.open like `tarfile.open("filename.tar.gz", "r:gz")`.  So I guess there should be a way to support on-the-fly decoding

**Comment by tmbdev** [comment]
@Lyken17 Tarfile nominally can perform random access via getmember, but if you use this with a gzipped file, it will simply reread the entire gzipped file from the beginning again each time you seek backwards. That is so inefficient as to be unusable. 

We could support WIDS on gzipped files by quietly decompressing the data to a temporary file; however, this has potential for race conditions and is hard to debug. I'll think about it.

Generally, it's best just to compress the individual files in a WebDataset file. The decoder will automatically decode .gz files for you anyway. So, instead of ".txt" or ".json", just store ".txt.gz" and ".json.gz".

**Comment by Lyken17** [comment]
I didn't know the internal stuff before. Thanks for the explaination! 

Still the best way so far is to save "uncompressed" tar files, tradeoff 5~15% more storage to keep compatbility.

**Comment by tmbdev** [comment]
If you want to use WIDS, then your best bet is uncompressed .tar files, but you can compress the contents. If you have lots of tiny files (e.g. Twitter messages), you can batch them, say, a list in a .json.gz file, and then unbatch them when loading.

If you use WebDataset, then of course, you can use .tar.gz freely.

I'll look into on-the-fly decompression but can't promise anything when it will be done.

**Comment by tmbdev** [comment]
A couple more comments:

The SAM datasets are not in order, meaning that corresponding .jpg and .json files are not necessarily adjacent in those tar files; WebDataset requires them to be adjacent. You can easily fix this by unpacking them and then tarring them up again with GNU tar "tar --sort=name -cvf archive.tar ." or "ls | sort | xargs tar ...".

Also, you can compress individual files inside a tar file and WebDataset will automatically decompress them for you. So, just put, say ".json.gz" instead of ".json" into the tar file and you'll get many of the same compression benefits you get from using a ZIP file.
