### ISSUE TITLE
Splitting features into separate archives

### ISSUE THREAD

**Issue by greaber** [webdataset/webdataset#335]
Our typical pattern for training is that we have various features that we compute on our data, and it is important not to recompute these features all the time since the computation is expensive.  Then we train models, and each model an request the features it wants.  If it wants features that haven't been computed yet, we can precompute those features or possibly they could be computed during the first epoch.

I'm looking at adopting webdataset, but the paradigm of keeping all features together seems pretty inconvenient for our workflow since when training any particular model, most of the features might not be needed, and also if we need to add a feature it would be better not to be forced to rewrite the entire dataset.  It seems like in the big data world people often prefer column-oriented storage to row-oriented storage for similar reasons.  Is there a way to achieve this with webdataset?  I.e., I would put each feature in a separate tar file and then read simultaneously from the different tar files I need?

Or if webdataset is a bad fit for my usecase, is there an alternative you recommend?

**Comment by tmbdev** [comment]
You use column-oriented storage in WebDataset and WIDS the same way you use it in any other big data library like Parquet: you simply open the corresponding shards and combine the features you get from them. In WIDS this is completely straightforward: you simply create two dataset instances and combine their features, as in: 

```
sample = wids1[index].update(wids2[index])
```

In WebDataset, you need to use the DataPipeline interface. It's fairly straightforward to implement this.

However, column stores are a bad idea for deep learning for two reasons. First, it greatly complicates data management, since you need to ensure that the shards for each column align. More importantly, you now pay for multiple seeks/server round trips on each sample on each epoch (or you need twice the storage hardware), which potentially becomes the limiting factor in terms of performance. Again, this is nothing specific to WebDataset, it is true for all such formats.

The recommended way of dealing with different choices of features for training is to generate a "row-oriented" dataset (a single set of shards with no columns) once before or during the first epoch. You can offload this to AIStore if you like.

So, again, WebDataset is as much of a "column store" as Parquet and you can use it the same way, but no matter which format or library you use, this is often not efficient for deep learning (despite Apache's claims to the contrary).

Note that there are special cases of "column stores" that are better handled in other ways anyway. For example, if you want to associate a new set of class labels or similarly small amounts of data, you are better off just storing that data in a database that you distribute to all clients, store on local SSD, and associate with the samples by key (not index):

````
sample = wids[index]
sample.update(database[sample["__key__"]])
```

**Comment by greaber** [comment]
Thanks.  Yeah, actually the solution that I am experimenting now is to put small data like labels in a single parquet file for the whole dataset and put the big binary features in tar files in shards.  I'm not sure if I really understand the distinction you are drawing between key and index though.  In any case, I will have some unique identifier of a given sample, and it seems easy enough to just make this an integer where these integers enumerate the dataset (but other options, like uuids would also work).  As for paying for multiple seeks/server round trips on each sample, isn't that the problem that sharding avoids because we process all the samples in a shard in a contiguous block of time (just paying the price that we have imperfect shuffling because we only shuffle the shards and the samples withing the shards but not samples between shards)?

**Comment by tmbdev** [comment]
> Thanks. Yeah, actually the solution that I am experimenting now is to put small data like labels in a single parquet file for the whole dataset and put the big binary features in tar files in shards.

Yes, that's the recommended solution for small annotations; there is even a method in webdataset to support this, `.associate`. The recommended format is LMDB or one of the DBM formats.

> I'm not sure if I really understand the distinction you are drawing between key and index though. 

The index is the numerical position in the dataset; it can change when you shuffle or process the dataset.

The key is the basename of the file in the .tar archive; it always uniquely identifies a sample no matter how you shuffle or preprocess.

**Comment by greaber** [comment]
Thanks!  I'm hoping I will be able to get adequate bandwidth from S3 or other S3-compatible object storage and not need to deal with the complexity of aistore, but we'll see (and I guess a potential advantage of aistore is that our servers come with a bunch of local nvme ssd that we might just be wasting if we keep everything in S3).  Without having tried it, it seems like it probably wouldn't really matter if I used parquet or LMDB or a DBM format from a performance perspective?  And as for shuffling, I was thinking that the idea of webdataset is that you don't really need full shuffling for good deep learning training since as long as you shuffle shards and shuffle within shards, that is good enough, even if you never shuffle between shards?  So then if I just pulled picked a shard and pulled the tar files for that shard (say there are five of them, if I need five features) and trained on the samples in that shard, it would be fine, and it wouldn't really be significantly slower than if I had all those features in one big tar file since S3 would do chunked multipart downloads anyway to maximize performance.  Is this the wrong way to think about it?  Not having to create special row-oriented datasets for each training situation would seem to avoid some complexity and extra space usage.  So the index/key distinction wouldn't really matter since the index would never change.  I will need to benchmark the speed though, and that seems relatively straightforward, but it may be trickier to understand how much of a penalty there is from imperfect shuffling, but my intuition is that it will not matter much.

**Comment by greaber** [comment]
Another possible issue is that we often only train on a slice of each sample.  Currently, we rely on numpy.memmap for this, but I also recently noticed that NVIDIA Dali supports GPUDirect slices of numpy npy files.  But this also doesn't seem straightforwardly achievable with webdataset unless we store everything as npy and unpack the shards prior to use, but again I'm not sure if this will be the bottleneck (but numpy.memmap slicing did give us a performance boost versus just loading the whole feature from NVME and then then slicing on CPU)
