### ISSUE TITLE
How can I store in wide dataset looks like input_image/output_image/metainfo ?

### ISSUE THREAD

**Issue by rybinsky** [webdataset/webdataset#375]
I have complicated dataset looks like:

`
input_image.jpg,
output_image.jpg,
metainfo.json
...
`
I can't do this:
pil_dataset = wds.WebDataset(url).to_tuple("jpg", "jpg", "json")

Is there any ideas how to do this?

**Comment by tmbdev** [comment]
I'm not sure what you mean. The WebDataset filename conventions exist so that grouping is possible. If you have arbitrary names like that, how do you know where one sample ends and the next one starts?

In any case, if your file names do not conform to standard WebDataset conventions, you have several options:

- you can use WebDataset(..., rename_files=some_function)
- you can explicitly construct a `DataPipeline` analogous to `WebDataset` and use a custom grouper

The `rename_files` variety is preferred because it will ensure that subsequent processing steps get the kind of file names they expect.
