### ISSUE TITLE
dataset repeating

### ISSUE THREAD

**Issue by LifuWang-66** [webdataset/webdataset#379]
I found that if I don't specify length through with_epoch(n)/with_length(n) or dataloader.length, the dataloader just iterate indefinitely. Is it intended or is there something wrong with my pipeline?

```
    train_dataset = (
        wds.WebDataset(
            args.dataset_urls,
            shardshuffle=1000,
            resampled=True,
            handler=wds.ignore_and_continue)
        .shuffle(100)
        .map(decode_txt)  
        .to_tuple('txt')
        .batched(args.batch_size, partial=False)
    )
    
    train_loader = wds.WebLoader(
        train_dataset, batch_size=None, shuffle=False, num_workers=args.workers
    )

```
Another question: If I want to use ddp with 2 gpus and the dataset has 10000 examples. Suppose batch size is 8, then I should set n=(10000/2)/8=625 in with_epoch(n), assuming that each gpu process half of the shards. Is my understanding correct?

**Comment by tmbdev** [comment]
Yes, this is as intended. Setting resampled=True will just resample shards indefinitely; with resampling, there is no obvious place to stop. You must use with_epoch(n) if you still want to use epochs.

Note that you don't need to use epochs, however. It really is preferable to treat all training as using an infinite source of samples, and then just separately periodically save and print progress, independent of dataset size.

That is, your look can look something like:

```
for batch in data:
    ...
    n += len(batch[0])
    if n > 10000:
       ...
```

instead of:

```
for epoch in range(1000):
    for batch in dl:
        ...
    print(...)
```

**Comment by garychan22** [comment]
@tmbdev hi, if i want to iter over the full dataset without resampling and read each batch with next(iter(wds_dataset)) instead of dataloader for some dynamic pre-processing along the training, how can i gurantee that there are always data available? thanks
