### ISSUE TITLE
Webdataset now returns a EOF value by default that causes an error in OpenCLIP

### ISSUE THREAD

**Issue by fartashf** [webdataset/webdataset#384]
The recent release 0.2.96 of webdataset has introduced a new argument to `tar_file_expander` called `eof_value` set by default to `{}` that is backward incompatible. Specifically, training in OpenCLIP results in this error:
```
  File "./src/training/data.py", line 281, in group_by_keys_nothrow
    fname, value = filesample["fname"], filesample["data"]
KeyError: 'fname'
```

Would it make sense to set the default value to None to keep the code backward compatible?

**Comment by tmbdev** [comment]
I'm not sure what happened there. We needed an EOF value to deal with the fact that a sample shouldn't be repeated infinitely. This looks like some other code didn't get updated properly. 

Can you provide a test case that reproduces this error?

**Comment by wanghao14** [comment]
Hi @tmbdev, I fine-tuned OpenCLIP on my own data in webdataset format, opened the 'resampled' for trainset, and encountered the same problem. Could you please review the logic of their [webdataset loading code](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip_train/data.py#L328) and provide some advice on how to resolve this issue? Thanks in advance.

**Comment by fartashf** [comment]
@wanghao14 The fix is to pass `eof_value=None` to `tar_file_expander` on this line:
https://github.com/mlfoundations/open_clip/blob/fc5a37b72d705f760ebbc7915b84729816ed471f/src/open_clip_train/data.py#L217
This is a breaking change from webdataset and not sure if the right solution to ask OpenCLIP to fix it or to ask webdataset to change the default value.

**Comment by wanghao14** [comment]
@fartashf Thanks for pointing it out. I reviewed the old version of webdataset and noticed that `eof_value` is a newly added feature (as you commented initially). I'm just not sure whether this modification affects the training process.

**Comment by tmbdev** [comment]
Sorry, I was away at a conference. 

The openclip code contains its own implementation of group_by_keys; I'm not entirely sure why. This is very rare. 

The solution is to do the same thing that `group_by_keys` does in the original library: test for whether you got {} and finish the current sample. That is, you need to add 2-3 lines to actually handle this situation.

https://github.com/webdataset/webdataset/blob/f0f2b00392ab41e64823263f04c57eaf1864baf2/webdataset/tariterators.py#L239

There is no way to avoid adding this logic to your code because without it, it's simply incorrect. That is, without checking for {}, if the user runs your code on a single shard with resampling, the `tar_file_iterator` returns the same file over and over again and any `group_by_keys_...` function will not work correctly.

If you think that there is a better way of handling this situation, please reopen this issue.

**Comment by Han-jiaxin** [comment]
you can add a judgment before this code “fname, value = filesample[”fname“], filesample[”data“]” to check for the presence of the “fname” and “data” keys:`
for filesample in data:
        
        if not isinstance(filesample, dict) or "fname" not in filesample or "data" not in filesample:
            if handler is not None:
                handler(f"Skipping malformed filesample: {filesample}")
            continue 
        fname, value = filesample["fname"], filesample["data"]`
