### ISSUE TITLE
Question: Costs and Pricing of Webdataset Writing to AWS S3 using Pipe Mode 

### ISSUE THREAD

**Issue by noamsgl** [webdataset/webdataset#391]
Hi,

The following code works to write a numpy array of 1000 samples to an S3 webdataset in Pipe mode.
  
```
import numpy as np
import webdataset as wds
from dotenv import load_dotenv
from tqdm import tqdm

assert load_dotenv("/home/ubuntu/.security/.s3-update.env")

data = np.random.rand(1000, 1000, 1000)

with wds.TarWriter("pipe:aws s3 cp - s3://my-bucket-name/test.tar") as sink:
    for i in tqdm(range(len(data))):  
        sink.write({"__key__": f"{i}", "data.npy": data[i]})
print("done")
```

My question is, how to estimate the AWS costs for two scenarios:
1. Running locally on my laptop?
2. Running on an EC2 instance in the same region as the S3 bucket?

The main thing I want to know is do I pay per sample or do I pay per pipe connection?
Thanks!

**Comment by tmbdev** [comment]
AWS doesn't know anything about samples; as far as it is concerned, you are just writing a stream to a bucket, if slowly. So, you're paying for ingress bandwidth and storage. But AWS may not charge for ingress bandwidth at all (Google doesn't).

However, the recommended way of writing shards is to local disk and then use "aws cp localfile.tar s3://my-bucket/shard-00123.tar". That's both because some object storage systems don't like small writes, and because you want the upload to happen only when the shard was created successfully.

Shardwriter has a special callback that gets called every time a shard is complete to let you do that.
