### ISSUE TITLE
Estimating Epoch Length with DDP in PyTorch Lightning

### ISSUE THREAD

**Issue by crscarpinteiro** [webdataset/webdataset#403]
I'm training a model using Distributed Data Parallel (DDP) with PyTorch Lightning and WebDataset, and I'm having trouble understanding how to set the epoch length to get accurate estimates of the time one epoch will take. Here's my current setup:
```
 num_gpus = torch.cuda.device_count() if torch.cuda.is_available() else 1  
    effective_batch_size = batch_size // num_gpus

    dataset = webdataset.WebDataset(file_names, shardshuffle=True, resampled=True,
                                    nodesplitter=webdataset.split_by_node).shuffle(100)

    dataset = dataset.decode(decode_fn)

    # Create DataLoader
    loader = webdataset.WebLoader(
        dataset, num_workers=num_workers, 
        pin_memory=True)
  
    loader = loader.batched(effective_batch_size, collation_fn=collate_fn)
    loader = loader.with_epoch(dataset_size // batch_size).with_length(dataset_size // batch_size)
```
Additionally, any insights on how to make this faster? I have shards that are 600MB each, containing 4096 samples, in total I have 13916. I have my dataset on S3.

**Comment by tmbdev** [comment]
## Your Code

Iterable datasets have no lengths associated with them according to PyTorch, so guessing the length and setting it using `.with_length(...)` is the only thing you can do. Note that calling code is not compliant with PyTorch, since IterableDataset isn't supposed to have a length, so this is a workaround for non-PyTorch compliant code outside WebDataset.

The only inefficiency I see in your code is that you are transferring single samples from the workers to the loader. In addition, you are not shuffling between shards from different workers. You could change your code to say:

```Python
    loader = webdataset.WebLoader(
        dataset.batched(32), num_workers=num_workers, 
        pin_memory=True)
  
    loader = loader.unbatched().shuffle(1000)
    loader = loader.batched(effective_batch_size, collation_fn=collate_fn)
```

The batching in the dataset here doesn't have anything to do with your final batch size, it just bundles together data for more efficient transfer from the workers to the loader.

If you care about performance, I recommend adding benchmark options to your code that replace the loader and trainer each with a mock implementation and measuring how fast things go. That is, for benchmarking the trainer, just keep giving it the same in-memory batch over and over again, and for benchmarking the loader just skip the inference/training steps altogether. See how many samples or batches per second you get for each to see where the bottleneck is.

## Alternatives

Using WebDataset in this way for distributed training is tricky in several ways, not just involving the length.

The simplest solution is to use `wids.ShardListDataset`, which makes multinode training work exactly like single node.

https://github.com/webdataset/webdataset/blob/main/examples/train-resnet50-multiray-wids.ipynb

If you want the benefits of purely sequential I/O (no local storage) and still want multinode training, the recommended approach is to use resampling:

https://github.com/webdataset/webdataset/blob/main/examples/train-resnet50-multiray-wds.ipynb

With resampled training, there are no epochs by default, but you can impose an epoch size using `with_epoch` (and if you want, set that epoch size as the length using `with_length`).

**Comment by crscarpinteiro** [comment]
Thank you for the quick answer! 
If I add the `loader = loader.unbatched().shuffle(1000)`  the machine runs out of memory. Do you have any idea why?
