### ISSUE TITLE
Path separator not decoded correctly

### ISSUE THREAD

**Issue by Rick-McCoy** [webdataset/webdataset#49]
I tried to open a local tar file in Windows 10, but the path separator was decoded incorrectly.

```
from itertools import islice
import webdataset as wds
dataset_path = os.path.join('dataset', 'dataset.tar)
dataset = wds.WebDataset(dataset_path)
for batch in islice(dataset, 3):
    print(batch.keys())
```

This should open the dataset as normal; however, this throws a `FileNotFoundError` with the following message: `FileNotFoundError: [Errno 2] No such file or directory: 'datasetdataset.tar'`

Manually changing the `dataset_path` variable to 

```
from itertools import islice
import webdataset as wds
dataset_path = '/'.join(['dataset', 'dataset.tar'])
dataset = wds.WebDataset(dataset_path)
for batch in islice(dataset, 3):
    print(batch.keys())
```

opens the dataset correctly.

**Comment by tmbdev** [comment]
I'm not sure why this is happening; os.path.join is supposed to use the platform-specific pathname separator.

Which version/distribution of Python are you using and how are you running it?

**Comment by Rick-McCoy** [comment]
As you said, Windows uses `\\` and Linux uses `/`. Manually changing the path separator from `\\` to `/` worked normally.

The python version is `3.7.8` and the webdataset version is `0.1.54`.

I isolated the whole setup in a virtualenv to ensure reproducibility.

**Comment by tmbdev** [comment]
I still don't understand the bug report. You're on Windows, and os.path.join should be using "\\" on Windows.

Your  version, on the other hand, explicitly and literally uses the Linux path separator "/", yet that is working on Windows.

The os.path.join call is exactly what should ensure portability.

That's why I'm wondering: what's the actual source of your Python distribution? Is it Conda for Windows? Is it Python running under MS-Ubuntu? Etc.

**Comment by Rick-McCoy** [comment]
Python, pip, all on Windows. When I tried it on WSL on the same machine, it obviously worked without manual replacement.

**Comment by tmbdev** [comment]
Can you just run

    >>> os.path.join("a", "b")

directly in Python and see what it outputs?

**Comment by Rick-McCoy** [comment]
![image](https://user-images.githubusercontent.com/26558631/113147137-6d6dcb00-926b-11eb-8903-a6cfa26b0308.png)

Nothing unusual.

**Comment by tmbdev** [comment]
OK, I'm mystified since the path joining works correctly when you call it directly, but not when called from within the library.

I'll keep the bug open to watch this and test on Windows (there is no test automation for Windows, so that has to be a manual check).

**Comment by Rick-McCoy** [comment]
Thanks for taking an interest in this issue. Looking forward to the next update :)

**Comment by grofte** [comment]
This is because of braceexpand

```python
import braceexpand
print(list(braceexpand.braceexpand('dataset\dataset.tar')))

>> ['datasetdataset.tar']
```

I think this would work for local files but I don't think it does with cloud locations:

```python
import braceexpand
from pathlib import Path, PureWindowsPath, PurePosixPath

path = Path('dataset/dataset{00..02}.tar')
print(path)
>> dataset/dataset{00..02}.tar
brace = list(braceexpand.braceexpand(str(path.name)))
print(brace)
>> ['dataset00.tar', 'dataset01.tar', 'dataset02.tar']
brace = [str(path.parent / b) for b in brace]
print(brace)
>> ['dataset/dataset00.tar', 'dataset/dataset01.tar', 'dataset/dataset02.tar']
```

Cloudpathlib might work for some cloud things but doesn't for ftp yet (dunno about http). os.sep would also give you issues with URL when on Windows as far as I can tell... 

This seems okay? 
```python
import braceexpand

path = 'dataset\dataset{00..02}.tar'
path = path.translate({92: 43})
print(path)
>> dataset+dataset{00..02}.tar
brace = list(braceexpand.braceexpand(path))
print(brace)
>> ['dataset+dataset00.tar', 'dataset+dataset01.tar', 'dataset+dataset02.tar']
brace = [b.translate({43: 92}) for b in brace]
print(brace)
>> ['dataset\\dataset00.tar', 'dataset\\dataset01.tar', 'dataset\\dataset02.tar']
```

**Comment by grofte** [comment]
To be honest I would prefer if the input was a list and then you could put braceexpand in the examples. And then we could also get the paths from glob or some other source.

**Comment by tmbdev** [comment]
The input can be a list; when you pass a list to WebDataset, it will not perform further expansion on it.

The input can also be an IterableDataset, in which case, WebDataset will iterate over it for a list of pathnames; that way, you can compute them dynamically.

When the input is a string, it is brace expanded.

There is really little reason to use backslash in path names on Windows either; forward slash is a full equivalent. Using paths with forward slashes is a good idea because it makes it easier to move the code between platforms and to move between the web and local file systems.  (For the same reason, it's a good idea to avoid braces, colons, and spaces in file names.)

**Comment by stunlocked1** [comment]
Are there any solutions to this?
